import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en"> 
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col 
                bg-gradient-to-br from-gray-50 via-white to-gray-100 
                dark:from-gray-950 dark:via-black dark:to-gray-950`}
            >
                {children}
                <Footer />
            </body>
        </html>
    );
}
